language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"

# command to run tests, e.g. python setup.py test
script: 
    coverage run --source respect setup.py test

# notifications based on http://docs.travis-ci.com/user/notifications/
notifications:
    email: false

after_success:
    coveralls
